version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8050:8050"
    volumes:
      - .:/code
      - ./config:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    expose:
      - "8050"
    command: bash -c "python manage.py migrate --run-syncdb && python manage.py runserver 0:8050"
    depends_on:
      - db
    volumes:
      - .:/code

  db:
    image: postgres:latest
    container_name: ps01